language: node_js
node_js:
  - "8.11.3"
cache:
  directories:
  - node_modules
before_install:
  - npm install -g firebase-tools
script:
  - echo "Deploying!!"
after_success:
  - npm run build
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master
